# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: User API CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        working-directory: UserManagement/
        run: dotnet restore
      - name: Build
        working-directory: UserManagement/
        run: dotnet build --no-restore
      - name: Test
        working-directory: UserManagement/
        run: dotnet test --no-build --verbosity normal
      - name: Build and Push Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: andybougard/fersoft
          tags: 1.0.1, latest
          dockerfile: UserManagement/Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
